# this stack is used to run dsiem with surrealdb and elasticsearch,
# with elasticsearch receiving copy of alarms.
# (normalized) events and alarm_events will only be stored in surrealdb.

# the differences between this and the `compose.yml` are the elasticsearch
# and kibana services, and the extra config for dsiem-esproxy to use both 
# surrealdb and elasticsearch.

# to use this stack, run `docker compose -f compose-with-es.yml up`
# and then install kibana dashboard using:
#
# cd /examples/elasticsearch && \
#   ./kbndashboard-import.sh localhost ./kibana/dashboard-siem.json 
#
# be aware that the dashboard will be missing siem_events index since 
# vector is not sending normalized events to elasticsearch.

version: "3"
services:

  surrealdb:
    container_name: surrealdb
    user: root
    image: surrealdb/surrealdb:latest
    ports:
    - "8000:8000"
    networks:
      - siemnet
    volumes:
      - surrealdb-data:/surrealdb-data
    command: ["start", "file:/surrealdb-data/surrealdb.db"]

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - cluster.routing.allocation.disk.threshold_enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.graph.enabled=false
      - xpack.watcher.enabled=false
      - xpack.security.enabled=false
      - http.cors.enabled=true
      - http.cors.allow-origin=*
    ports:
      - 9200:9200
    networks:
      - siemnet
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - xpack.monitoring.ui.container.elasticsearch.enabled=false
    ports:
      - 5601:5601
    networks:
      - siemnet
    depends_on:
      - elasticsearch

  dsiem:
    container_name: dsiem-frontend
    image: defenxor/dsiem-rs:latest
    environment:
      - DSIEM_MODE=cluster-frontend
      - DSIEM_NODE=dsiem-frontend-0
      - DSIEM_MSQ=nats://dsiem-nats:4222
      - DSIEM_PORT=8080
      - DSIEM_DEBUG=false
      - DSIEM_WEB_ESURL=http://localhost:9200
      - DSIEM_WEB_KBNURL=http://localhost:5601
      - DSIEM_MAXEPS=50000
    ports:
      - "8080:8080"
    networks:
      - siemnet
    volumes:
      - ./conf/dsiem:/dsiem/configs

  dsiem-backend:
    container_name: dsiem-backend
    image: defenxor/dsiem-rs:latest
    environment:
      - DSIEM_MODE=cluster-backend
      - DSIEM_NODE=dsiem-backend-0
      - DSIEM_DEBUG=true
      - DSIEM_FRONTEND=http://dsiem:8080
      - DSIEM_MSQ=nats://dsiem-nats:4222
      - DSIEM_RELOAD_BACKLOGS=false
      - DSIEM_MAXEPS=5000
    networks:
      - siemnet
    volumes:
      - dsiem-log:/dsiem/logs
  nats:
    container_name: dsiem-nats
    image: nats:1.3.0-linux
    networks:
      - siemnet

  vector:
    container_name: vector
    image: timberio/vector:0.37.0-alpine
    networks:
      - siemnet
    volumes:
      - ./conf/vector/central:/etc/vector
      - suricata-log:/var/log/suricata
    command: ["--config-dir", "/etc/vector", "--watch-config"]

  vector-sidecar:
    container_name: vector-sidecar
    image: timberio/vector:0.37.0-alpine
    networks:
      - siemnet
    volumes:
      - ./conf/vector/dsiem-sidecar:/etc/vector
      - dsiem-log:/var/log/dsiem
    command: ["--config-dir", "/etc/vector", "--watch-config"]

  dsiem-esproxy:
    container_name: dsiem-esproxy
    image: ghcr.io/mmta/dsiem-esproxy:latest
    environment:
      - DSIEM_ESPROXY_USE_ELASTICSEARCH=true
      - DSIEM_ESPROXY_USE_SURREALDB=true
      - DSIEM_ESPROXY_ELASTICSEARCH=http://elasticsearch:9200
      - DSIEM_ESPROXY_SURREALDB=http://surrealdb:8000
    networks:
      - siemnet
    ports:
      - "8181:8181"
    command: ["-v", "serve"]

  suricata:
    container_name: suricata
    image: defenxor/suricata:1710
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    command:
      [
        "/bin/bash",
        "-c",
        'chown -R suri /var/log/suricata && /usr/bin/suricata -v -i ${PROMISC_INTERFACE?"this environment variable must be set"}'
      ]
    volumes:
      - suricata-log:/var/log/suricata

volumes:
  es-data:
  surrealdb-data:
  dsiem-log:
  suricata-log:
networks:
  siemnet:
