version: "3"
services:

  surrealdb:
    container_name: surrealdb
    user: root
    image: surrealdb/surrealdb:latest
    ports:
    - "8000:8000"
    networks:
      - siemnet
    volumes:
      - surrealdb-data:/surrealdb-data
    command: ["start", "file:/surrealdb-data/surrealdb.db"]

  dsiem:
    container_name: dsiem-frontend
    image: defenxor/dsiem-rs:latest
    environment:
      - DSIEM_MODE=cluster-frontend
      - DSIEM_NODE=dsiem-frontend-0
      - DSIEM_MSQ=nats://dsiem-nats:4222
      - DSIEM_PORT=8080
      - DSIEM_DEBUG=false
      - DSIEM_WEB_ESURL=http://localhost:9200
      - DSIEM_WEB_KBNURL=http://localhost:5601
      - DSIEM_MAXEPS=50000
    ports:
      - "8080:8080"
    networks:
      - siemnet
    volumes:
      - ./conf/dsiem:/dsiem/configs

  dsiem-backend:
    container_name: dsiem-backend
    image: defenxor/dsiem-rs:latest
    environment:
      - DSIEM_MODE=cluster-backend
      - DSIEM_NODE=dsiem-backend-0
      - DSIEM_DEBUG=true
      - DSIEM_FRONTEND=http://dsiem:8080
      - DSIEM_MSQ=nats://dsiem-nats:4222
      - DSIEM_RELOAD_BACKLOGS=false
      - DSIEM_MAXEPS=5000
    networks:
      - siemnet
    volumes:
      - dsiem-log:/dsiem/logs
  nats:
    container_name: dsiem-nats
    image: nats:1.3.0-linux
    networks:
      - siemnet

  vector:
    container_name: vector
    image: timberio/vector:0.37.0-alpine
    networks:
      - siemnet
    volumes:
      - ./conf/vector/central:/etc/vector
      - suricata-log:/var/log/suricata
    command: ["--config-dir", "/etc/vector", "--watch-config"]

  vector-sidecar:
    container_name: vector-sidecar
    image: timberio/vector:0.37.0-alpine
    networks:
      - siemnet
    volumes:
      - ./conf/vector/dsiem-sidecar:/etc/vector
      - dsiem-log:/var/log/dsiem
    command: ["--config-dir", "/etc/vector", "--watch-config"]

  dsiem-esproxy:
    container_name: dsiem-esproxy
    image: mmta/dsiem-esproxy:latest
    environment:
      - DSIEM_ESPROXY_ELASTICSEARCH=http://elasticsearch:9200
      - DSIEM_ESPROXY_USE_SURREALDB=true
      - DSIEM_ESPROXY_USE_ELASTICSEARCH=false
      - DSIEM_ESPROXY_SURREALDB=http://surrealdb:8000
    networks:
      - siemnet
    ports:
      - "8181:8181"
    command: ["-v", "serve"]

  suricata:
    container_name: suricata
    image: defenxor/suricata:1710
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
      - NET_RAW
    command:
      [
        "/bin/bash",
        "-c",
        'chown -R suri /var/log/suricata && /usr/bin/suricata -v -i ${PROMISC_INTERFACE?"this environment variable must be set"}'
      ]
    volumes:
      - suricata-log:/var/log/suricata

volumes:
  surrealdb-data:
  dsiem-log:
  suricata-log:
networks:
  siemnet:
